ci(workspace): add projectId

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -55,21 +55,23 @@ jobs:
 
       - name: Fetch secrets from Infisical
         env:
-          INFISICAL_CLIENT_ID: ${{ secrets.INFISICAL_CLIENT_ID }}
-          INFISICAL_CLIENT_SECRET: ${{ secrets.INFISICAL_CLIENT_SECRET }}
+          CLIENT_ID: ${{ secrets.INFISICAL_CLIENT_ID }}
+          CLIENT_SECRET: ${{ secrets.INFISICAL_CLIENT_SECRET }}
+          PROJECT_ID: ${{ secrets.INFISICAL_PROJECT_ID }}
         run: |
           INFISICAL_TOKEN=$(infisical login \
             --method=universal-auth \
-            --client-id="$INFISICAL_CLIENT_ID" \
-            --client-secret="$INFISICAL_CLIENT_SECRET" \
+            --client-id="${{ secrets.INFISICAL_CLIENT_ID }}" \
+            --client-secret="${{ secrets.INFISICAL_CLIENT_SECRET }}" \
             --domain="https://eu.infisical.com" \
             --plain)
 
-          test -n "$INFISICAL_TOKEN"
+          if [ -z "$INFISICAL_TOKEN" ]; then echo "Login failed"; exit 1; fi
 
           infisical export \
             --token=$INFISICAL_TOKEN \
             --domain https://eu.infisical.com \
+            --projectId="$PROJECT_ID" \
             --env=prod \
             --path=/apps/me \
             --silent > .env
